'use strict';
const router = require('express').Router();
router.use('/auth',        require('./auth.routes'));
router.use('/users',       require('./users.routes'));
router.use('/surveys',     require('./surveys.routes'));
router.use('/respondents', require('./respondents.routes'));
router.use('/public',      require('./responses.routes'));
router.use('/results',     require('./results.routes'));
router.use('/eval',        require('./eval.routes'));
router.use('/audit',       require('./audit.routes'));
router.use('/lgpd',        require('./lgpd.routes'));
router.use('/push',        require('./push.routes'));
router.use('/org',         require('./org.routes'));
module.exports = router;
